### ISSUE TITLE
Start Up Problem

### ISSUE THREAD

**Issue by TomMitch94** [joshjcarrier/minecontrol#31]
As soon as I run the program I get an error message that tells me that the application cannot be run. I get the following error message:
![image](https://cloud.githubusercontent.com/assets/8092690/3498373/bd94b180-05f4-11e4-98bc-9ad47198aca6.png)

**Comment by chelleons** [comment]
Same here, could it be due to a new version of Java?

**Comment by joshjcarrier** [comment]
The certificate used to sign Java archives during deployment expired. A new certificate has been created and Minecontrol has been re-signed.
